import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.sonarqube)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.koin.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.androidx.room)
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
            // Required when using NativeSQLiteDriver
            linkerOpts.add("-lsqlite3")
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.room.sqlite.wrapper)
        }

        commonMain.dependencies {
            implementation(libs.bundles.compose.core)
            implementation(libs.bundles.lifecycle)
            implementation(libs.bundles.navigation)
            implementation(project.dependencies.platform(libs.ktor.bom))
            implementation(libs.bundles.ktor.common)
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.bundles.koin.common)
            implementation(libs.bundles.coil)
            implementation(libs.bundles.paging)
            implementation(libs.bundles.room)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.napier)
            implementation(libs.compose.multiplatform.media.player)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }

    koinCompiler {
        userLogs = true
    }
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}

android {
    namespace = "com.gameverse.app.shared"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    dependencies {
        debugImplementation(libs.compose.uiTooling)
    }
}

val generateBuildConfig = tasks.register("generateBuildConfig") {
    group = "build"
    description = "Generates BuildConfig.kt with API keys"
    val outputDir = layout.buildDirectory.dir("generated/source/buildConfig/commonMain/kotlin")
    val localPropertiesFile = layout.projectDirectory.file("../local.properties")

    inputs.file(localPropertiesFile).optional()
    outputs.dir(outputDir)

    doLast {
        val localProperties = Properties().apply {
            val file = localPropertiesFile.asFile
            if (file.exists()) {
                file.inputStream().use { load(it) }
            }
        }
        val rawgApiKey = localProperties.getProperty("rawgApiKey").orEmpty()

        val outputFile = outputDir.get().file("com/gameverse/app/config/BuildConfig.kt").asFile
        outputFile.parentFile.mkdirs()

        val content = """
            package com.gameverse.app.config

            /**
             * Generated BuildConfig - DO NOT EDIT MANUALLY
             * Generated by generateBuildConfig task from local.properties
             */
            @Suppress("UNUSED_PARAMETER")
            object BuildConfig {
                const val RAWG_API_KEY: String = "$rawgApiKey"
            }
        """.trimIndent()

        outputFile.writeText(content)
    }
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildConfig.map { it.outputs.files })
        }
    }
}


