import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.sonarqube)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.koin.compiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.androidx.room)
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
            // Required when using NativeSQLiteDriver
            linkerOpts.add("-lsqlite3")
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.room.sqlite.wrapper)
        }

        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.jetbrains.navigation3.ui)
            implementation(libs.jetbrains.lifecycle.viewmodelNavigation3)
            implementation(project.dependencies.platform(libs.ktor.bom))
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.ktor.client.contentNegotiation)
            implementation(libs.ktor.client.resources)
            implementation(libs.ktor.client.logging)
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.koin.compose.navigation)
            implementation(libs.koin.annotations)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.napier)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor3)
            implementation(libs.kotlinx.datetime)
            implementation(libs.androidx.paging.common)
            implementation(libs.androidx.paging.compose)
            implementation(libs.compose.multiplatform.media.player)
            implementation(libs.androidx.room.runtime)
            implementation(libs.androidx.sqlite.bundled)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
    }

    koinCompiler {
        userLogs = true
    }
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}

android {
    namespace = "com.gameverse.app"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    dependencies {
        debugImplementation(libs.compose.uiTooling)
    }
}

tasks.register("generateBuildConfig") {
    group = "build"
    description = "Generates BuildConfig.kt with API keys"
    val outputFile = layout.buildDirectory.file("generated/ksp/commonMain/kotlin/com/gameverse/app/config/BuildConfig.kt")
    val localPropertiesFile = layout.projectDirectory.file("../local.properties")

    outputs.file(outputFile)

    doLast {
        val localProperties = Properties().apply {
            localPropertiesFile.asFile.inputStream().use { load(it) }
        }
        val rawgApiKey = localProperties.getProperty("rawgApiKey").orEmpty()

        val content = """
            package com.gameverse.app.config

            /**
             * Generated BuildConfig - DO NOT EDIT MANUALLY
             * Generated by generateBuildConfig task from local.properties
             */
            @Suppress("UNUSED_PARAMETER")
            object BuildConfig {
                const val RAWG_API_KEY: String = "$rawgApiKey"
            }
        """.trimIndent()

        outputFile.get().asFile.parentFile.mkdirs()
        outputFile.get().asFile.writeText(content)
        println("Generated ${outputFile.get().asFile}")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn("generateBuildConfig")
}

tasks.matching { it.name.startsWith("ksp") }.configureEach {
    dependsOn("generateBuildConfig")
}

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/ksp/commonMain/kotlin"))
        }
    }
}

